### ISSUE TITLE
Milestone 4

### ISSUE THREAD

**Issue by ismailbhinder** [UBC-MDS/DSCI522-2425-group31_age-group-prediction#81]
- [x] Abstract some code from your scripts to functions in a separate file, and write tests for those functions
- [x] Address feedback to improve the project (Make CHANGELOG.md)
- [x] Create a Makefile to act as a driver script to rule them all

**Comment by Rashidikn1** [comment]
CHANGELOG.md added, closing the issue!
